### ISSUE TITLE
Refine Windows installation instructions

### ISSUE THREAD

**Issue by wheleph** [wheleph/nttt#65]
When I tried to install NTTT on a Windows 10 laptop I discovered that `nttt` executable is not added to path by default (and hence is not available in command line).

Acceptance criteria:
- The issue with missing `nttt` executable is investigated
- Installation instructions are updated accordingly

**Comment by robertjank** [comment]
No problems on my Windows (8.1) machine. That is because my PATH environment variable contains %LOCALAPPDATA%\Programs\Python\Python39\Scripts\ and %LOCALAPPDATA%\Programs\Python\Python39\ (where the latter directory is the location of my Python 3.9 installation). The former directory contains the nttt.exe and nttt-script.py created by pip3. If I recall correctly, the Python installer has a checkbox which allows you to determine whether the installer should extend the PATH environment variable or not.
