### ISSUE TITLE
*** of volunteer acknowledgement shown in published version

### ISSUE THREAD

**Issue by robertjank** [wheleph/nttt#70]
The acknowledgements are added right below the last string. When the last step ends with a sentence, the *** are shown in the published version, instead of the line that's supposed to be inserted between the last string and the acknowledgements:
[vols-issue.PNG](https://rpf-translation.slack.com/files/U9PCHABEU/F02FWM64DTM/vols-issue.png)
[vols-issue2.PNG](https://rpf-translation.slack.com/files/U9PCHABEU/F02FWM68VFV/vols-issue2.png)
[vols-issue-live.PNG](https://rpf-translation.slack.com/files/U9PCHABEU/F02FWM6C6SF/vols-issue-live.png)

When the last string is a tag, --- /challenge --- for example, everything is fine in the live version:
[vols-ok.PNG](https://rpf-translation.slack.com/files/U9PCHABEU/F02FPURP4SJ/vols-ok2.png)
[vols-ok-live.PNG](https://rpf-translation.slack.com/files/U9PCHABEU/F02FWM8FUFL/vols-ok.png)

Adding a space before the acknowledgements may resolve this issue.

**Comment by robertjank** [comment]
The projects with the problem are [I made you a book](https://github.com/raspberrypilearning/i-made-you-a-book) and [Rocket](https://github.com/raspberrypilearning/blender-rocket). Project [Turtle race](https://github.com/raspberrypilearning/turtle-race) is the one without the problem.

**Comment by wheleph** [comment]
This is a weird issue. Normally '***' in markdown is rendered as a horizontal line even if there's no blank line above it:
![Screenshot 2021-10-03 at 20 24 33](https://user-images.githubusercontent.com/2729981/135764819-ac3f2be7-83ba-497e-9b3d-235bc324aa7c.png)

I'm wondering if there's a way for us to reproduce it somehow (i. e. to generate HTML from MD in the "RPF" way).

Otherwise, we'll just need to make a blind fix and ask Maja or Nina to try it.

**Comment by robertjank** [comment]
I agree that it is weird and that it should work without the blank line. Let's just add the blank line, because it is not doing any harm in case it is not needed.
