### ISSUE TITLE
Ensure "---" tags are in English

### ISSUE THREAD

**Issue by pcolladosoto** [wheleph/nttt#9]
## Description
We need to ensure tags in between "---" are in English.

## Applicable to
+ All `.md` files.

## Acceptance criteria
+ Ensure that tags `--- x --- and --- /x ---` are left intact in the translated `.md` files. Specifically the following problems and their combinations should be detected and corrected:
    + Missing single dash: `-- x --`.
    + Translated tag text: `--- y ---`. Where *y* is the translated version of *x* in the target language.
    + Missing spaces: `---x---`.

## Open questions
+ Can we assume that `--- x ---` and `--- /x ---` tags are located in dedicated paragraphs?

## Ideas
+ Prevent translators from changing the translation for these entries.
    + Can this be achieved in CrowdIn?
        + We run into the same problems as #7.
    + It won't work for already translated projects.
+ Revert changes in these entries.
    + This requires access to the original (English) version of the file.
    + Assumes these tags are always on a separate line.
    + Will automatically fix problems like 3 dashes having been replaced with 2 dashes.

## Issues
+ What about tags like `title`? The title tag spans 3 lines:

    + ```yml
        ---
        title: What you will learn
        ---
       ```
+ See issue #13.

**Comment by pcolladosoto** [comment]
As in issue #7, maybe having the original english files as an additional input, would help with these corrections as well (especially the “translated tag text” one).

#### Original author: Manos Zeakis (@ezeakis)

**Comment by wheleph** [comment]
@majamanojlovic in order to implement this feature properly I need to know additional details about how Crowdin interprets .md files.

My assumption (please correct me if I'm wrong):
- Every paragraph (not line!) from the original English text (https://raw.githubusercontent.com/raspberrypilearning/stickers/master/en/step_1.md) becomes a separate string to translate in Crowdin UI (https://crowdin.com/translate/rpf-stickers/1958/en-uk?filter=basic&value=0)

How do you make strings hidden?
![Screenshot 2020-11-15 at 17 38 36](https://user-images.githubusercontent.com/2729981/99189350-756c1900-2769-11eb-8517-dd710e0c852a.png)

Do you have any idea why Crowdin puts `\---` instead of `---` and also merges these tags into a single line `\--- hints \--- \--- hint \---`. Example: https://raw.githubusercontent.com/raspberrypilearning/boat-race/l10n_master/uk-UA/step_3.md

**Comment by majamanojlovic** [comment]
@wheleph sorry for not replying sooner!

1. I am honestly quite confused about this one. I could have sworn each sentence, or a line in some cases, is treated as a separate string but looking at the text of Stickers in Crowdin, it seems like entire paragraphs are actually strings. For example, this whole paragraph is treated as one string, even though it consists of two sentences:

![par2](https://user-images.githubusercontent.com/49232422/100254170-df3eac80-2f39-11eb-9020-b2bab5e7e6da.PNG)

But then here we again have two sentences in the same paragraph, but each is treated as a separate string:

![par1](https://user-images.githubusercontent.com/49232422/100254248-f7aec700-2f39-11eb-8e73-066e0edd9550.PNG)

Or am I missing something?

2. We hide the strings manually in project's settings in Crowdin.

3. I'm afraid I don't know why Crowdin adds \ to tags. As for merging into a single line - I think it's because there is no space between the tags in the English version.

English:
![eng](https://user-images.githubusercontent.com/49232422/100253118-a3571780-2f38-11eb-9588-0c7e3beddeba.PNG)

vs Ukrainian:
![ukr](https://user-images.githubusercontent.com/49232422/100253129-a6ea9e80-2f38-11eb-9f61-e6114ea69e02.PNG)

**Comment by wheleph** [comment]
Original code of NTTT contains some replacements for that weird Crowdin output. For instance it replaces `\---` with `---`.

But the code also contains replacement `## ---` -> `---`. @majamanojlovic do you have any idea why we have that kind of replacement? What do we try to fix with it?

**Comment by wheleph** [comment]
@majamanojlovic never mind. It has something to do with fixing of title tags (https://raw.githubusercontent.com/raspberrypilearning/stickers/l10n_master/uk-UA/step_1.md):

```
## \--- collapse \---

## title: Нотатки керівника клубу
```

**Comment by wheleph** [comment]
@majamanojlovic can you tell me how translations end up in `l10n_master`? Is there a background process that continuously pulls data from Crowdin and puts it into the branch or do you pull this data from Crowdin explicitly before publishing?

**Comment by majamanojlovic** [comment]
@wheleph Crowdin and l10n_master are connected via integrations, which are quite unreliable. In theory, the integrations are supposed to continuously pull data from Crowdin and add it to the branch, but they are often disconnecting. Whenever we go publish a project, we check the integration, and if it's broken (which often is the case) we need to re-connect it with the repo in GitHub again.
