### ISSUE TITLE
Add upstream remote

### ISSUE THREAD

**Issue by sra405** [wheleph/nttt#92]
Hi 👋 firstly a huge thanks are in order, you've taken a small internal tool and collectively ran with it 👏 

We're looking at automating various parts of our translations workflow and this tool is currently on our hitlist to run in an automated fashion. As a result we'll need to lock down specific versions under our Github org. By no means feel we're taking anything away from you, I've added a contributors section and wanted to visibly show thanks to everyone that's helped.

Ongoing work can keep happening here too but to help bring new changes into our version being automated I'd recommend [following this](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/configuring-a-remote-repository-for-a-fork) to add our repo as an upstream remote (essentially making this repo a fork). The upstream will be [this repo](https://github.com/raspberrypilearning/nttt) in our learning org 😄 

Then when you want to merge some stuff up open a PR against whichever branch in this repo going into `main` in `raspberrypilearning/nttt` and we'll review and merge up 👍 

Thanks again and I hope you guys continue contributing because it's AWESOME! 🎉 🥳

**Comment by wheleph** [comment]
Glad to meet you @sra405 !

I think that this is terrific that our work has been promoted to the [original repo](https://github.com/raspberrypilearning/nttt) and hence will be a part of future automation.

@robertjank, maybe we should archive this repository for the following reasons:
- To avoid duplication
- It doesn't have any visual "fork" icon in the Github UI which might lead to confusion
- For further improvements in NTTT we could make fresh personal forks as needed

@sra405 you might also want to check our non-code assets, maybe some of them will be useful in the upstream as well:
- [Wiki pages](https://github.com/wheleph/nttt/wiki)
- [Issues](https://github.com/wheleph/nttt/issues). It seems like you've [already fixed](https://github.com/raspberrypilearning/nttt/commit/f27196b1754fc088c77e9e6f6d3322b2eea506f6) [one](https://github.com/wheleph/nttt/issues/75) :)
- [Releases](https://github.com/wheleph/nttt/releases)

Finally, don't hesitate to reach out if you have any questions related to the existing code or future improvements.

**Comment by wheleph** [comment]
[This is](https://github.com/wheleph/nttt/wiki/Development-workflow#source-code-organization) where I almost started crying:

<img width="932" alt="Screenshot 2023-02-02 at 21 51 23" src="https://user-images.githubusercontent.com/2729981/216435471-ba59ddb4-0618-4668-be84-75af5b6c5383.png">

**Comment by sra405** [comment]
Nice to meet you too @wheleph 😄 Thanks for pointing me towards the non-code assets too, I'll have a think how we can utilise those too. Ultimately though I don't want to just take over, it's great what you guys have done and it'd be awesome to collaborate it the future 😁 

> * It doesn't have any visual "fork" icon in the Github UI which might lead to confusion

My understanding is (and I've never done it so not 100%) if you add the original repo as the upstream it'll add the github fork for you 😄 it should be a case of [doing this](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/configuring-a-remote-repository-for-a-fork) 🤞.

> Finally, don't hesitate to reach out if you have any questions related to the existing code or future improvements.

I'm sure I'll have plenty of questions don't worry. From what I've seen so far it looks like nice clean code 💪

**Comment by robertjank** [comment]
Hi Scott (@sra405),
Thanks for the kind words! Most credits should go to Volodymyr (@wheleph) who wrote most of the extensions of nttt. And like him, I am very happy that our work is picked up by you and your colleagues!
I have sent you an invitation for a repository that I created (and maintained ;-)) which we used to test new features and also to detect regression. Maybe this is also useful for you (although it is quite a hassle to check changes, because a huge number of files are involved, so hopefully you can design something a little easier).
And, similar to Volodymyr, I am always willing to help in any way to improve nttt even more!

**Comment by robertjank** [comment]
@wheleph, I fully agree that we should archive this repository. Maybe [this](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) can be used to mark this repository as fork, but it is probably not worth the effort.

**Comment by wheleph** [comment]
Thank you for the links guys but I still cannot see how it's possible to setup fork-upstream relationship in Github retroactively so that it's visible in UI.

The [page](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/configuring-a-remote-repository-for-a-fork) suggested by @sra405 describes how to setup a remote in a _local_ repository (clone). I don't think it's possible to somehow "push" those settings so that a repo in Github becomes aware that it's a fork of another repository. Actually, I have it since day one but it doesn't affect Github UI:

```
~/pro/nttt (main =)$ git remote -v
origin	git@github.com:wheleph/nttt.git (fetch)
origin	git@github.com:wheleph/nttt.git (push)
upstream	https://github.com/raspberrypilearning/nttt (fetch)
upstream	https://github.com/raspberrypilearning/nttt (push)
```

The [page](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) suggested by @robertjank works for repos with already established fork-upstream relationship.

So I've added the deprecation note:

<img width="929" alt="Screenshot 2023-02-05 at 20 15 06" src="https://user-images.githubusercontent.com/2729981/216837406-e5cb0995-dc3f-478d-9638-66e6df214533.png">


My next step is to archive the repo.

@sra405 for collaboration I think we can use Github issues in the upstream repo or the [Slack channel](https://app.slack.com/client/T98R40CV9/G0176UY7D7A) that we used back in the day.
